/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.formulariojson.sistemacombateturno;

import java.awt.Color;
import java.awt.Image;
import java.util.HashSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Rafael
 */
public class TelaCombate extends javax.swing.JFrame {

    /**
     * Creates new form TelaCombate
     */
    public TelaCombate() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Espada = new javax.swing.JButton();
        Magia = new javax.swing.JButton();
        pocao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Arco = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itens = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Vidaboss = new javax.swing.JLabel();
        nivelBoss = new javax.swing.JLabel();
        nivelPersonagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Espada.setBackground(new java.awt.Color(0, 0, 0));
        Espada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Espada.setForeground(new java.awt.Color(255, 0, 0));
        Espada.setText("ESPADA");
        Espada.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        Espada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspadaActionPerformed(evt);
            }
        });

        Magia.setBackground(new java.awt.Color(0, 0, 0));
        Magia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Magia.setForeground(new java.awt.Color(204, 0, 0));
        Magia.setText("MAGIA");
        Magia.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        Magia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagiaActionPerformed(evt);
            }
        });

        pocao.setBackground(new java.awt.Color(0, 0, 0));
        pocao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pocao.setForeground(new java.awt.Color(255, 0, 0));
        pocao.setText("POÇÃO");
        pocao.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        pocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pocaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIDA");

        Arco.setBackground(new java.awt.Color(0, 0, 0));
        Arco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Arco.setForeground(new java.awt.Color(255, 0, 0));
        Arco.setText("ARCO");
        Arco.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        Arco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArcoActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/personagem.png"))); // NOI18N

        Estado.setEditable(false);
        Estado.setBackground(new java.awt.Color(0, 0, 0));
        Estado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Estado.setForeground(new java.awt.Color(255, 255, 255));
        Estado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Estado.setActionCommand("null");
        Estado.setBorder(null);
        Estado.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("CULPA");

        itens.setEditable(false);
        itens.setBackground(new java.awt.Color(0, 0, 0));
        itens.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itens.setForeground(new java.awt.Color(51, 255, 0));
        itens.setText("3");
        itens.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("POÇÔES");

        nivelBoss.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        nivelBoss.setForeground(new java.awt.Color(0, 255, 51));
        nivelBoss.setText(" I I I I I I I I I I I I I I I I I I I I");

        nivelPersonagem.setFont(new java.awt.Font("Impact", 1, 14)); // NOI18N
        nivelPersonagem.setForeground(new java.awt.Color(0, 255, 51));
        nivelPersonagem.setText("I I I I I I I I I I");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Espada, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Magia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Arco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(106, 106, 106))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 119, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivelBoss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Vidaboss)
                        .addGap(4, 4, 4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nivelPersonagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itens, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Vidaboss)
                    .addComponent(nivelBoss))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Espada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Arco, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Magia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pocao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nivelPersonagem))))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EspadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspadaActionPerformed
        Espadada();
    }//GEN-LAST:event_EspadaActionPerformed

    private void ArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArcoActionPerformed
        TiroArco();
    }//GEN-LAST:event_ArcoActionPerformed

    private void MagiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagiaActionPerformed
        Tiromagia();
    }//GEN-LAST:event_MagiaActionPerformed

    private void pocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pocaoActionPerformed
       regenegar();
    }//GEN-LAST:event_pocaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCombate().setVisible(true);
            }
        });
    }
    
    public Personagem personagem = new Personagem(10);
    public Personagem Boss = new Personagem(30);
    public int Recuperar = 3;
    
    public void Espadada(){
         int[] opcoes = {0, 2,3,4,6,8};
         int dano = opcoes[(int)(Math.random() * opcoes.length)];
         Boss.setHp(Boss.getHp() - dano);
         conferirVida();
         if(dano>0){
         Estado.setText("Voce causou " + dano + " de dano por espadada");
         ataqueBoss();
         conferirVida();    
         }
         else{
         Estado.setText("A culpa se esquivou de voce "); 

         ataqueBoss();
         conferirVida();    

         }
    }    
        public void TiroArco(){
        int[] opcoes = {0, 3, 4};
        int dano = opcoes[(int)(Math.random() * opcoes.length)];
        Boss.setHp(Boss.getHp() - dano);
        conferirVida();
         if(dano>0){
                Estado.setText("Sua Flecha causou " + dano + " de dano");
                ataqueBoss();
                conferirVida();    
         }
         else{
                Estado.setText("A culpa se esquivou de voce ");
                ataqueBoss();
                conferirVida();    
         }
    }
        public void Tiromagia(){
        int[] opcoes = {0, 6};
        int dano = opcoes[(int)(Math.random() * opcoes.length)];
        Boss.setHp(Boss.getHp() - dano);
        conferirVida();
        if(dano>0){
             Estado.setText("Voce causou 5 de dano por magia");
             ataqueBoss();
             conferirVida();    
         }
         else{
            Estado.setText("A culpa se esquivou de voce");
            ataqueBoss();
            conferirVida();    
         }
}
        
        public void regenegar(){
        if(personagem.getHp()<10){
            if(Recuperar > 0){
                Estado.setText("Voce recuperou 3 de vida ");
                personagem.setHp(personagem.getHp()+ 3);
                Recuperar --;
                itens.setText(Recuperar + "");
                conferirVida();                
                ataqueBoss();
                conferirVida();    
            }
            else{
                Estado.setText("Voce não possui itens de cura");
            }
        }
        else{
                if(Recuperar > 0){
                Estado.setText("Sua vida esta cheia ");    
            }
            else{
                Estado.setText("Voce não possui itens de cura");
            }
        }
        }
        
        public void conferirVida(){
            if(personagem.getHp()>10){
                personagem.setHp(10);
                nivelPersonagem.setText("I I I I I I I I I I");
            }
            if(personagem.getHp()== 9){
                nivelPersonagem.setText("I I I I I I I I I");
            }
            if(personagem.getHp()== 8){
                nivelPersonagem.setText("I I I I I I I I");
            }
            if(personagem.getHp()== 7){
                nivelPersonagem.setText("I I I I I I I");
            }
            if(personagem.getHp()>6){
                nivelPersonagem.setForeground(Color.green);
            }
            if(personagem.getHp()== 6){
                nivelPersonagem.setForeground(Color.yellow);
                nivelPersonagem.setText("I I I I I I");
            }
            if(personagem.getHp()== 5){
                nivelPersonagem.setText("I I I I I");
            }
            if(personagem.getHp()== 4){
                nivelPersonagem.setText("I I I I");
            }
            if(personagem.getHp()>3 && personagem.getHp() <=6 ){
                nivelPersonagem.setForeground(Color.yellow);

            }
            if(personagem.getHp()== 3){
                nivelPersonagem.setForeground(Color.red);
                nivelPersonagem.setText("I I I");
            }
            if(personagem.getHp()== 2){
                nivelPersonagem.setText("I I");
            }
            if(personagem.getHp()== 1){
                nivelPersonagem.setText("I");
            }
            if(personagem.getHp()<= 0 ){
                nivelPersonagem.setText("");
                   JOptionPane.showMessageDialog(null,"Voce foi derrotado!!! \n"
                            + " a cupa lentamente toma conta de ti\n"
                            + " e voce cai nos proprios pensamentos\n"
                           + "enquanto a escuridão toma conta da sua\n"
                           + "cabeça");
            }
            
            // Boss
            
            if(Boss.getHp()>27 && Boss.getHp() <30){
                nivelBoss.setText("I I I I I I I I I I I I I I I I I I I");
            }
            if(Boss.getHp()>24 && Boss.getHp()<=27){
                nivelBoss.setText("I I I I I I I I I I I I I I I I I");
            }
            if(Boss.getHp()>21 && Boss.getHp()<=24){
                nivelBoss.setText("I I I I I I I I I I I I I I I I");
            }
            if(Boss.getHp()>19 && Boss.getHp()<=21){
                nivelBoss.setText("I I I I I I I I I I I I I I I");
            }
            if(Boss.getHp()>16 && Boss.getHp()<=19){
                nivelBoss.setForeground(Color.yellow);
                nivelBoss.setText("I I I I I I I I I I I I I I");
            }
            if(Boss.getHp()>13 && Boss.getHp()<=16){
                nivelBoss.setText("I I I I I I I I I I I I I");
            }
            if(Boss.getHp()>10 && Boss.getHp()<=13){
                nivelBoss.setText("I I I I I I I I I I I");
            }
            if(Boss.getHp()>7 && Boss.getHp()<=10){
                nivelBoss.setForeground(Color.pink);
                nivelBoss.setText("I I I I I I I I I I");
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/personagemQuaMorto.png")));
            }
            if(Boss.getHp()>5 && Boss.getHp()<=7){
                nivelBoss.setText("I I I I I I I I I");
            }
            if(Boss.getHp()>3 && Boss.getHp()<=5){
                nivelBoss.setForeground(Color.red);
                nivelBoss.setText("I I I I I");
            }
            if(Boss.getHp()>0 && Boss.getHp()<=3){
                nivelBoss.setForeground(Color.red);
                nivelBoss.setText("I I I");
            }
            if(Boss.getHp()<=0){
                Timer timer = new Timer(2500,e ->{
                nivelBoss.setText("");                    
                Estado.setText("A dor acabou");
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/personagemMorto.png")));
              });
            timer.setRepeats(false);
            timer.start();

                   JOptionPane.showMessageDialog(null,"Voce se livrou da culpa!!! \n"
                            + " ainda consegue sentir a presença dela,\n"
                            + " mas agora ela não te afeta, e então\n"
                           + "em um dia qualquer voce acorada e não sente\n"
                           + "mais ela, na verdade... você ja não lembra dela");
            }
        }
        
        
        public void ataqueBoss(){
        int[] opcoes = {0,1,3};
        int dano = opcoes[(int)(Math.random() * opcoes.length)];
        personagem.setHp(personagem.getHp()- dano);
        if(dano == 0 ){
        Timer timer =new Timer(2500,e ->{
            Estado.setText("A culpa errou o ataque");
         });
        timer.setRepeats(false);
        timer.start();            
        }
        else if(dano == 1){
        Timer timer =new Timer(2500,e ->{
            Estado.setText("A culpa entra na sua mente, 1 de dano");
         });
        timer.setRepeats(false);
        timer.start();
        }
        else{
        Timer timer = new Timer(2500,e ->{
        Estado.setText("Voce relembra aquele dia, 3 de dano");
         });
        timer.setRepeats(false);
        timer.start();
        }      
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Arco;
    private javax.swing.JButton Espada;
    private javax.swing.JTextField Estado;
    private javax.swing.JButton Magia;
    private javax.swing.JLabel Vidaboss;
    private javax.swing.JTextField itens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nivelBoss;
    private javax.swing.JLabel nivelPersonagem;
    private javax.swing.JButton pocao;
    // End of variables declaration//GEN-END:variables
}
